# permissions for end users to edit layouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: layout-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: placement-operator
    app.kubernetes.io/part-of: placement-operator
    app.kubernetes.io/managed-by: kustomize
  name: layout-editor-role
rules:
- apiGroups:
  - core.cnskunkworks.io
  resources:
  - layouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.cnskunkworks.io
  resources:
  - layouts/status
  verbs:
  - get
